name: linux_proc
description: Parse Linux process and service information
version: 0.0.1
publish_to: none
repository: https://github.com/wstrange/systemd_ui/linux_proc

environment:
  sdk: ^3.2.6

dependencies:
  dbus: ^0.7.10
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
