name: linux_proc
description: Parse Linux process and service information
version: 0.0.2
repository: https://github.com/wstrange/linux_proc

environment:
  sdk: ^3.2.6

dependencies:
  dbus: ^0.7.10

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
