name: dtop
description: A sample command-line application.
version: 0.0.1
publish_to: none
repository: https://github.com/wstrange/linux_proc

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  dart_console: ^4.1.0
  linux_proc:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
